// Inspect lineage JSON — a project feature, independent of any use case.
//
// Two states. First state: a picker, nothing else — no schema, no version, no
// implementation vocabulary. Second state, once something is loaded: a title,
// a stage checklist, a verification summary, then three tabs (Execution /
// Checks / Technical details). Schema versions, artifact IDs and provenance
// internals live only in Technical details — a normal user does not need them
// to read what happened.

import { el, link, note, statusBadge, definitionList, table, stageLabel, hash } from "../components/format.js";
import { renderLineage, stageState, normalizeContext } from "../components/stages.js";
import { renderChecks } from "../components/checks.js";
import { renderLinks } from "../components/links.js";
import { renderLoader } from "../components/loader.js";
import { data, state, render } from "../app.js";

const CHECKLIST_STAGES = [
  ["intent", "Intent"],
  ["provider_response", "Provider response"],
  ["route", "Route"],
  ["transaction_construction", "Transaction"],
  ["settlement", "Settlement"],
];

const TABS = [
  ["Execution", "execution"],
  ["Checks", "checks"],
  ["Technical details", "technical"],
];

function stageChecklist(context) {
  const list = el("ul", { class: "checklist" });
  for (const [key, label] of CHECKLIST_STAGES) {
    const st = stageState(context, key);
    const glyph = st === "observed" ? "✓" : st === "not_applicable" ? "–" : st === "candidate" ? "◈" : "?";
    list.append(
      el("li", { class: `checklist-${st}` }, [
        el("span", { "aria-hidden": "true", text: `${glyph} ` }),
        el("span", { text: label }),
      ]),
    );
  }
  return list;
}

function verificationSummary(report) {
  const counts = {
    PASS: report.summary?.pass || 0,
    FAIL: report.summary?.fail || 0,
    CANDIDATE: report.summary?.candidate || 0,
    UNKNOWN: report.summary?.unknown || 0,
    NOT_APPLICABLE: report.summary?.not_applicable || 0,
  };
  const row = el("div", { class: "summary-row" });
  for (const status of ["PASS", "FAIL", "CANDIDATE", "UNKNOWN", "NOT_APPLICABLE"]) {
    row.append(
      el("span", {}, [statusBadge(status), el("span", { class: "mono", text: ` ${counts[status]}` })]),
    );
  }
  return row;
}

function technicalDetails(root, context, bundleSet) {
  root.append(el("h2", { text: "Technical details" }));
  root.append(
    note(
      "Implementation metadata: schema versions, artifact identity, and where each observation's bytes came from. Not needed to read the execution.",
    ),
  );
  root.append(
    definitionList([
      ["artifact id", context.provenance?.artifact_id],
      ["provider", context.provider],
      ["context schema", context.schema_version],
      ["lineage schema", bundleSet.lineage?.schema_version],
    ]),
  );

  const stages = context.provenance?.stages || [];
  if (stages.length) {
    root.append(el("h3", { text: "provenance" }));
    root.append(
      table(
        ["stage", "source", "path", "sha256"],
        stages.map((p) =>
          el("tr", {}, [
            el("td", { class: "mono", text: stageLabel(p.stage) }),
            el("td", { class: "mono", text: p.source }),
            el("td", { class: "mono muted", text: p.source_path || "—" }),
            el("td", {}, [hash(p.sha256)]),
          ]),
        ),
      ),
    );
  }

  const unresolved = bundleSet.lineage?.unresolved || [];
  if (unresolved.length) {
    root.append(el("h3", { text: "where the verifier stops" }));
    root.append(
      table(
        ["field", "reason"],
        unresolved.map((u) =>
          el("tr", {}, [el("td", { class: "mono", text: u.field }), el("td", { text: u.reason })]),
        ),
      ),
    );
  }
}

function pickerScreen(root) {
  root.append(el("p", { class: "eyebrow", text: "Inspect lineage JSON" }));
  root.append(el("h1", { text: "Inspect a lineage" }));
  root.append(el("p", { class: "lede", text: "Drop a lineage.json generated by the Rust CLI." }));

  renderLoader(root, { source: data.lineage.source }, (loaded) => {
    if (loaded.lineage) data.lineage.lineage = loaded.lineage;
    if (loaded.context) data.lineage.context = loaded.context;
    if (loaded.verification) data.lineage.verification = loaded.verification;
    data.lineage.source = "local";
    state.inspectMode = "result";
    state.inspectPanel = "execution";
    state.link = null;
    render();
  });

  if (data.lineage.lineage) {
    root.append(
      el("p", { class: "prose" }, [
        "Don't have a file yet? ",
        el("button", {
          class: "control",
          type: "button",
          text: "View the bundled sample",
          onclick: () => {
            state.inspectMode = "result";
            state.inspectPanel = "execution";
            render();
          },
        }),
      ]),
    );
  }
}

function resultScreen(root) {
  const context = normalizeContext(data.lineage.context || {});
  const report = data.lineage.verification;
  const panel = state.inspectPanel || "execution";

  const title = context.provider
    ? `${context.provider}${context.provenance?.surface ? " · " + context.provenance.surface : ""}`
    : "Execution";

  root.append(el("p", { class: "eyebrow", text: "Inspect lineage JSON" }));
  root.append(el("h1", { text: title }));

  if (data.lineage.source === "local") {
    root.append(el("p", { class: "local-badge", text: "your file — stayed in this browser" }));
  } else {
    root.append(
      note(
        "Showing the bundled sample: a synthetic provider response run through the real pipeline. The genuine DFlow reference lineage is not published — its context embeds the requester's wallet pubkey.",
      ),
    );
  }

  root.append(stageChecklist(context));
  if (report) root.append(verificationSummary(report));

  const tabs = el("nav", { class: "subnav" });
  for (const [label, id] of TABS) {
    tabs.append(
      el("a", { href: `#/inspect?panel=${id}`, text: label, "aria-current": panel === id ? "page" : undefined }),
    );
  }
  root.append(tabs);

  if (panel === "checks") {
    if (report) {
      renderChecks(
        root,
        data.lineage,
        state,
        (status) => {
          state.status = status;
          render();
        },
        { hideSummary: true },
      );
    } else {
      root.append(note("No verification report loaded for this artifact."));
    }
  } else if (panel === "technical") {
    technicalDetails(root, context, data.lineage);
  } else {
    renderLineage(root, data.lineage, state, (stage) => {
      state.stage = stage;
      render();
    });
    if ((data.lineage.lineage?.links || []).length) {
      renderLinks(root, data.lineage, state, (id) => {
        state.link = id;
        render();
      });
    }
  }

  root.append(el("p", { class: "prose" }, [link("#/inspect?panel=load", "Load a different file →")]));
}

export function renderInspect(root) {
  const hasResult = state.inspectMode === "result" && data.lineage.lineage;
  if (!hasResult) {
    pickerScreen(root);
    return;
  }
  resultScreen(root);
}
